const ErrorTypes = {
    UNAUTHORISED: 'UNAUTHORISED',
    INTERNAL_SERVER_ERROR: 'INTERNAL SERVER ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    UNIQUE_VIOLATION: 'UNIQUE VIOLATION',
    NOT_FOUND: 'NOT_FOUND',
    UNEXPECTED_RESPONSE: 'UNEXPECTED_RESPONSE'
};

export default ErrorTypes;


